import { base, fg, bg, ui, syntax} from './colors';
import { semanticTokenColors } from './templates/semanticTokenColors';
import { textmateTokenColors } from './templates/textmateTokenColors';

export default () => {
  return {
    "name": "Dark Petrol - Dev",
    "type": "dark",
    "semanticHighlighting": true,
    "semanticTokenColors": semanticTokenColors,
    "tokenColors": textmateTokenColors,
    "colors": {
      // Contrast colors
      // "contrastActiveBorder"    : ui.border.primary.hex(),
      // "contrastBorder"          : ui.border.primary.hex(),
      // Base Colors
      "focusBorder"             : ui.border.primary.alpha(0).hex(),
      "foreground"              : fg.hex(),
      "disabledForeground"      : ui.panel.primary.inactive.foreground.hex(),
      // "widget.border"           : ui.border.primary.hex(),
      "selection.background"    : ui.panel.primary.active.background.hex(),
      "descriptionForeground"   : fg.hex(),
      "errorForeground"         : ui.message.error.normal.foreground.hex(),
      "icon.foreground"         : fg.hex(),
      // "sash.hoverBorder"        : fg.hex(),
      // Window Border
      // "window.activeBorder"     : ui.panel.primary.active.border.hex(),
      // "window.inactiveBorder"   : ui.panel.primary.inactive.border.hex(),
      // Text Colors
      "textBlockQuote.background"   : ui.panel.primary.normal.background.hex(),
      "textBlockQuote.border"       : ui.panel.primary.normal.border.hex(),
      "textCodeBlock.background"    : ui.panel.primary.normal.background.hex(),
      "textLink.activeForeground"   : ui.message.info.active.foreground.hex(),
      "textLink.foreground"         : ui.message.info.normal.foreground.hex(),
      "textPreformat.foreground"    : fg.hex(),
      "textPreformat.background"    : ui.panel.primary.normal.background.hex(),
      "textSeparator.foreground"    : fg.hex(),
      // Action Colors
      "toolbar.hoverBackground"           : ui.bar.primary.hovered.background.hex(),
      "toolbar.hoverOutline"              : ui.bar.primary.normal.border.hex(),
      "toolbar.activeBackground"          : ui.bar.primary.active.background.hex(),
      "editorActionList.background"       : ui.bar.secondary.normal.background.hex(),
      "editorActionList.foreground"       : ui.bar.secondary.normal.foreground.hex(),
      "editorActionList.focusForeground"  : ui.bar.secondary.active.foreground.hex(),
      "editorActionList.focusBackground"  : ui.bar.secondary.active.background.hex(),
      // Button Control
      "button.background"                 : ui.input.button.normal.background.hex(),
      "button.foreground"                 : ui.input.button.normal.foreground.hex(),
      "button.border"                     : ui.input.button.normal.border.hex(),
      "button.separator"                  : ui.input.button.normal.border.hex(),
      "button.hoverBackground"            : ui.input.button.hovered.background.hex(),
      "button.secondaryForeground"        : ui.input.button.normal.foreground.hex(),
      "button.secondaryBackground"        : ui.input.button.normal.background.hex(),
      "button.secondaryHoverBackground"   : ui.input.button.hovered.background.hex(),
      "checkbox.background"               : ui.input.checkbox.normal.background.hex(),
      "checkbox.foreground"               : ui.input.checkbox.normal.foreground.hex(),
      "checkbox.border"                   : ui.input.checkbox.normal.border.hex(),
      "checkbox.selectBackground"         : ui.input.checkbox.active.background.hex(),
      "checkbox.selectBorder"             : ui.input.checkbox.active.border.hex(),
      "radio.activeForeground"            : ui.input.checkbox.active.foreground.hex(),
      "radio.activeBackground"            : ui.input.checkbox.active.background.hex(),
      "radio.activeBorder"                : ui.input.checkbox.active.border.hex(),
      "radio.inactiveForeground"          : ui.input.checkbox.inactive.foreground.hex(),
      "radio.inactiveBackground"          : ui.input.checkbox.inactive.background.hex(),
      "radio.inactiveBorder"              : ui.input.checkbox.inactive.border.hex(),
      "radio.inactiveHoverBackground"     : ui.input.checkbox.hovered.background.hex(),
      // Dropdown Control
      "dropdown.background"       : ui.input.button.normal.background.hex(),
      "dropdown.listBackground"   : ui.input.button.normal.background.hex(),
      "dropdown.border"           : ui.input.button.normal.border.hex(),
      "dropdown.foreground"       : ui.input.button.normal.foreground.hex(),
      // Input Control
      "input.background"                  : ui.input.button.normal.background.hex(),
      "input.border"                      : ui.input.button.normal.border.hex(),
      "input.foreground"                  : ui.input.button.normal.foreground.hex(),
      "input.placeholderForeground"       : ui.input.button.inactive.foreground.hex(),
      "inputOption.activeBackground"      : ui.input.checkbox.active.background.hex(),
      "inputOption.activeBorder:"         : ui.input.checkbox.active.border.hex(),
      "inputOption.activeForeground:"     : ui.input.checkbox.active.foreground.hex(),
      "inputOption.hoverBackground:"      : ui.input.checkbox.hovered.background.hex(),
      "inputValidation.errorBackground"   : ui.message.error.normal.background.hex(),
      "inputValidation.errorForeground"   : ui.message.error.normal.foreground.hex(),
      "inputValidation.errorBorder"       : ui.message.error.normal.border.hex(),
      "inputValidation.infoBackground"    : ui.message.info.normal.background.hex(),
      "inputValidation.infoForeground"    : ui.message.info.normal.foreground.hex(),
      "inputValidation.infoBorder"        : ui.message.info.normal.border.hex(),
      "inputValidation.warningBackground" : ui.message.warning.normal.background.hex(),
      "inputValidation.warningForeground" : ui.message.warning.normal.foreground.hex(),
      "inputValidation.warningBorder"     : ui.message.warning.normal.border.hex(),
      // Scrollbar Control
      "scrollbar.shadow"                  : ui.dialog.first.normal.background.hex(),
      "scrollbarSlider.activeBackground"  : ui.dialog.first.active.background.hex(),
      "scrollbarSlider.background"        : ui.dialog.first.normal.background.hex(),
      "scrollbarSlider.hoverBackground"   : ui.dialog.first.hovered.background.hex(),
      // Badge
      "badge.foreground"  : ui.input.button.normal.foreground.hex(),
      "badge.background"  : ui.input.button.normal.background.hex(),
      // Progress Bar
      "progressBar.background": ui.message.info.normal.background.hex(),
      // List and Trees
      "list.activeSelectionBackground"        : ui.panel.secondary.active.background.hex(),
      "list.activeSelectionForeground"        : ui.panel.secondary.active.foreground.hex(),
      "list.activeSelectionIconForeground"    : ui.panel.secondary.active.foreground.hex(),
      "list.dropBackground"                   : ui.panel.secondary.normal.background.hex(),
      "list.focusBackground"                  : ui.panel.secondary.active.background.hex(),
      "list.focusForeground"                  : ui.panel.secondary.active.foreground.hex(),
      "list.focusHighlightForeground"         : ui.panel.secondary.hovered.foreground.hex(),
      "list.focusOutline"                     : ui.panel.secondary.hovered.border.hex(),
      "list.focusAndSelectionOutline"         : ui.panel.secondary.active.border.hex(),
      "list.highlightForeground"              : ui.panel.secondary.hovered.foreground.hex(),
      "list.hoverBackground"                  : ui.panel.secondary.hovered.background.hex(),
      "list.hoverForeground"                  : ui.panel.secondary.hovered.foreground.hex(),
      "list.inactiveSelectionBackground"      : ui.panel.secondary.inactive.background.hex(),
      "list.inactiveSelectionForeground"      : ui.panel.secondary.inactive.foreground.hex(),
      "list.inactiveSelectionIconForeground"  : ui.panel.secondary.inactive.foreground.hex(),
      "list.inactiveFocusBackground"          : ui.panel.secondary.inactive.background.hex(),
      "list.inactiveFocusOutline"             : ui.panel.secondary.inactive.border.hex(),
      "list.invalidItemForeground"            : ui.message.error.normal.foreground.hex(),
      "list.errorForeground"                  : ui.message.error.normal.foreground.hex(),
      "list.warningForeground"                : ui.message.warning.normal.foreground.hex(),
      "listFilterWidget.background"           : ui.input.checkbox.normal.background.hex(),
      "listFilterWidget.outline"              : ui.input.checkbox.normal.border.hex(),
      "listFilterWidget.noMatchesOutline"     : ui.message.error.normal.border.hex(),
      "listFilterWidget.shadow"               : ui.input.checkbox.normal.background.hex(),
      "list.filterMatchBackground"            : ui.message.success.normal.background.hex(),
      "list.filterMatchBorder"                : ui.message.success.normal.border.hex(),
      "list.deemphasizedForeground"           : ui.input.checkbox.normal.background.hex(),
      "list.dropBetweenBackground"            : ui.input.checkbox.normal.background.hex(),
      "tree.indentGuidesStroke"               : ui.panel.secondary.normal.border.hex(),
      "tree.inactiveIndentGuidesStroke"       : ui.panel.secondary.inactive.border.hex(),
      "tree.tableColumnsBorder"               : ui.panel.secondary.normal.border.hex(),
      "tree.tableOddRowsBackground"           : ui.panel.secondary.normal.background.hex(),
      // Activity Bar
      "activityBar.background"            : ui.panel.secondary.normal.background.hex(),
      "activityBar.dropBorder"            : ui.panel.secondary.normal.border.hex(),
      "activityBar.foreground"            : ui.panel.secondary.normal.foreground.hex(),
      "activityBar.inactiveForeground"    : ui.panel.secondary.inactive.foreground.hex(),
      "activityBar.border"                : ui.panel.secondary.normal.border.hex(),
      "activityBarBadge.background"       : ui.dialog.first.normal.background.hex(),
      "activityBarBadge.foreground"       : ui.dialog.first.normal.foreground.hex(),
      "activityBar.activeBorder"          : ui.panel.secondary.active.border.hex(),
      "activityBar.activeBackground"      : ui.panel.secondary.active.background.hex(),
      "activityBar.activeFocusBorder"     : ui.panel.secondary.active.border.hex(),
      "activityBarTop.foreground"         : ui.panel.secondary.normal.foreground.hex(),
      "activityBarTop.activeBorder"       : ui.panel.secondary.active.border.hex(),
      "activityBarTop.inactiveForeground" : ui.panel.secondary.inactive.border.hex(),
      "activityBarTop.dropBorder"         : ui.panel.secondary.normal.border.hex(),
      "activityBarTop.background"         : ui.panel.secondary.normal.background.hex(),
      "activityBarTop.activeBackground"   : ui.panel.secondary.active.background.hex(),
      // Profiles
      "profileBadge.background" : ui.dialog.first.normal.background.hex(),
      "profileBadge.foreground" : ui.dialog.first.normal.foreground.hex(),
      "profiles.sashBorder"     : ui.dialog.first.normal.border.hex(),
      // Side Bar
      "sideBar.background"              : ui.panel.tertiary.normal.background.hex(),
      "sideBar.foreground"              : ui.panel.tertiary.normal.foreground.hex(),
      "sideBar.border"                  : ui.panel.tertiary.normal.border.hex(),
      "sideBar.dropBackground"          : ui.panel.tertiary.normal.background.hex(),
      "sideBarTitle.foreground"         : ui.panel.tertiary.normal.foreground.hex(),
      "sideBarSectionHeader.background" : ui.panel.primary.normal.background.hex(),
      "sideBarSectionHeader.foreground" : ui.panel.primary.normal.foreground.hex(),
      "sideBarSectionHeader.border"     : ui.panel.primary.normal.border.hex(),
      "sideBarActivityBarTop.border"    : ui.panel.primary.normal.border.hex(),
      "sideBarTitle.background"         : ui.panel.primary.normal.background.hex(),
      "sideBarStickyScroll.background"  : ui.input.checkbox.normal.background.hex(),
      "sideBarStickyScroll.border"      : ui.input.checkbox.normal.border.hex(),
      "sideBarStickyScroll.shadow"      : ui.input.checkbox.normal.background.hex(),
      // Minimap
      "minimap.findMatchHighlight"            : ui.message.success.hovered.background.hex(),
      "minimap.selectionHighlight"            : ui.message.info.hovered.background.hex(),
      "minimap.errorHighlight"                : ui.message.error.hovered.background.hex(),
      "minimap.warningHighlight"              : ui.message.warning.hovered.background.hex(),
      "minimap.background"                    : ui.dialog.first.hovered.background.hex(),
      "minimap.selectionOccurrenceHighlight"  : ui.message.info.hovered.background.hex(),
      "minimap.foregroundOpacity"             : ui.dialog.first.hovered.foreground.hex(),
      "minimap.infoHighlight"                 : ui.message.info.hovered.foreground.hex(),
      "minimapSlider.background"              : ui.dialog.first.active.background.hex(),
      "minimapSlider.hoverBackground"         : ui.dialog.first.hovered.background.hex(),
      "minimapSlider.activeBackground"        : ui.dialog.first.active.background.hex(),
      "minimapGutter.addedBackground"         : ui.git.added.hovered.background.hex(),
      "minimapGutter.modifiedBackground"      : ui.git.modified.hovered.background.hex(),
      "minimapGutter.deletedBackground"       : ui.git.deleted.hovered.background.hex(),
      // Editor Groups and Tabs
      "editorGroup.border"                    : ui.panel.secondary.normal.border.hex(),
      "editorGroup.dropBackground"            : ui.panel.secondary.normal.background.hex(),
      "editorGroupHeader.noTabsBackground"    : ui.panel.secondary.normal.background.hex(),
      "editorGroupHeader.tabsBackground"      : ui.dialog.first.normal.background.hex(),
      "editorGroupHeader.tabsBorder"          : ui.dialog.first.normal.border.hex(),
      "editorGroupHeader.border"              : ui.dialog.first.normal.border.hex(),
      "editorGroup.emptyBackground"           : ui.dialog.first.normal.background.hex(),
      "editorGroup.focusedEmptyBorder"        : ui.dialog.first.active.border.hex(),
      "editorGroup.dropIntoPromptForeground"  : ui.dialog.first.hovered.foreground.hex(),
      "editorGroup.dropIntoPromptBackground"  : ui.dialog.first.hovered.background.hex(),
      "editorGroup.dropIntoPromptBorder"      : ui.dialog.first.hovered.border.hex(),
      "tab.activeBackground"                  : ui.panel.tertiary.active.background.hex(),
      "tab.unfocusedActiveBackground"         : ui.panel.tertiary.inactive.background.hex(),
      "tab.activeForeground"                  : ui.panel.tertiary.active.foreground.hex(),
      "tab.border"                            : ui.panel.tertiary.normal.border.hex(),
      "tab.activeBorder"                      : ui.panel.tertiary.active.border.hex(),
      "tab.selectedBorderTop"                 : ui.panel.tertiary.active.border.hex(),
      "tab.selectedBackground"                : ui.panel.tertiary.active.background.hex(),
      "tab.selectedForeground"                : ui.panel.tertiary.active.foreground.hex(),
      "tab.dragAndDropBorder"                 : ui.panel.tertiary.hovered.border.hex(),
      "tab.unfocusedActiveBorder"             : ui.panel.tertiary.normal.border.hex(),
      "tab.activeBorderTop"                   : ui.panel.tertiary.active.border.hex(),
      "tab.unfocusedActiveBorderTop"          : ui.panel.tertiary.active.border.hex(),
      "tab.lastPinnedBorder"                  : ui.panel.tertiary.normal.border.hex(),
      "tab.inactiveBackground"                : ui.panel.tertiary.normal.background.hex(),
      "tab.unfocusedInactiveBackground"       : ui.panel.tertiary.normal.background.hex(),
      "tab.inactiveForeground"                : ui.panel.tertiary.inactive.foreground.hex(),
      "tab.unfocusedActiveForeground"         : ui.panel.tertiary.active.foreground.hex(),
      "tab.unfocusedInactiveForeground"       : ui.panel.tertiary.inactive.foreground.hex(),
      "tab.hoverBackground"                   : ui.panel.tertiary.hovered.background.hex(),
      "tab.unfocusedHoverBackground"          : ui.panel.tertiary.hovered.background.hex(),
      "tab.hoverForeground"                   : ui.panel.tertiary.hovered.foreground.hex(),
      "tab.unfocusedHoverForeground"          : ui.panel.tertiary.hovered.foreground.hex(),
      "tab.hoverBorder"                       : ui.panel.tertiary.hovered.border.hex(),
      "tab.unfocusedHoverBorder"              : ui.panel.tertiary.hovered.border.hex(),
      "tab.activeModifiedBorder"              : ui.git.modified.active.border.hex(),
      "tab.inactiveModifiedBorder"            : ui.git.modified.inactive.border.hex(),
      "tab.unfocusedActiveModifiedBorder"     : ui.git.modified.inactive.border.hex(),
      "tab.unfocusedInactiveModifiedBorder"   : ui.git.modified.inactive.border.hex(),
      "editorPane.background"                 : ui.panel.primary.normal.background.hex(),
      "sideBySideEditor.horizontalBorder"     : ui.panel.primary.normal.border.hex(),
      "sideBySideEditor.verticalBorder"       : ui.panel.primary.normal.border.hex(),
      // Editor Colors
      "editor.background"                       : ui.panel.primary.normal.background.hex(),
      "editor.foreground"                       : ui.panel.primary.normal.foreground.hex(),
      "editorLineNumber.foreground"             : ui.panel.primary.normal.foreground.hex(),
      "editorLineNumber.activeForeground"       : ui.panel.primary.active.foreground.hex(),
      "editorLineNumber.dimmedForeground"       : ui.panel.primary.inactive.foreground.hex(),
      "editorCursor.background"                 : ui.panel.primary.hovered.background.hex(),
      "editorCursor.foreground"                 : ui.panel.primary.hovered.foreground.hex(),
      "editorMultiCursor.primary.foreground"    : ui.panel.primary.hovered.foreground.hex(),
      "editorMultiCursor.primary.background"    : ui.panel.primary.hovered.background.hex(),
      "editorMultiCursor.secondary.foreground"  : ui.panel.secondary.hovered.foreground.hex(),
      "editorMultiCursor.secondary.background"  : ui.panel.secondary.hovered.background.hex(),
      "editor.placeholder.foreground"           : ui.panel.primary.normal.foreground.hex(),
      "editor.selectionBackground"              : ui.panel.primary.active.foreground.alpha(0.35).hex(), 
      "editor.selectionForeground"              : ui.panel.primary.active.foreground.hex(),
      "editor.inactiveSelectionBackground"      : ui.panel.primary.inactive.background.alpha(0.35).hex(),
      "editor.selectionHighlightBackground"     : ui.panel.primary.hovered.background.alpha(0.35).hex(),
      "editor.selectionHighlightBorder"         : ui.panel.primary.hovered.border.alpha(0.35).hex(),
      "editor.wordHighlightBackground"          : ui.message.info.normal.background.alpha(0.35).hex(),
      // "editor.wordHighlightBorder"              : fg.hex(),
      "editor.wordHighlightStrongBackground"    : ui.message.info.normal.background.alpha(0.35).hex(),
      // "editor.wordHighlightStrongBorder"        : base.red.hex(),
      "editor.wordHighlightTextBackground"      : ui.message.info.normal.background.alpha(0.35).hex(),
      // "editor.wordHighlightTextBorder"          : base.red.hex(),
      "editor.findMatchBackground"              : ui.message.success.normal.background.alpha(0.35).hex(),
      "editor.findMatchForeground"              : ui.message.success.normal.foreground.hex(),
      "editor.findMatchHighlightForeground"     : ui.message.success.normal.foreground.hex(),
      "editor.findMatchHighlightBackground"     : ui.message.success.normal.background.alpha(0.35).hex(),
      "editor.findRangeHighlightBackground"     : ui.message.success.normal.foreground.hex(),
      // "editor.findMatchBorder"                  : base.red.hex(),
      // "editor.findMatchHighlightBorder"         : base.red.hex(),
      // "editor.findRangeHighlightBorder"         : base.red.hex(),
      "search.resultsInfoForeground"            : ui.message.success.normal.foreground.hex(),
      "searchEditor.findMatchBackground"        : ui.message.success.normal.background.hex(),
      // "searchEditor.findMatchBorder"            : base.red.hex(),
      // "searchEditor.textInputBorder"            : base.red.hex(),
      "editor.hoverHighlightBackground"         : ui.message.info.hovered.background.alpha(0.35).hex(),
      "editor.lineHighlightBackground"          : ui.message.info.normal.background.alpha(0.35).hex(),
      // "editor.lineHighlightBorder"              : base.red.hex(),
      // "editorWatermark.foreground"              : base.red.hex(),
      // "editorUnicodeHighlight.border"           : base.red.hex(),
      // "editorUnicodeHighlight.background"       : base.red.hex(),
      "editorLink.activeForeground"             : ui.message.info.normal.foreground.hex(),
      "editor.rangeHighlightBackground"         : ui.message.info.normal.background.alpha(0.35).hex(),
      // "editor.rangeHighlightBorder"             : base.red.hex(),
      "editor.symbolHighlightBackground"        : ui.message.info.normal.background.alpha(0.35).hex(),
      // "editor.symbolHighlightBorder"            : base.red.hex(),
      // "editorWhitespace.foreground"             : base.red.hex(),
      // "editorIndentGuide.background"            : base.red.hex(),
      // "editorIndentGuide.background1"           : base.red.hex(),
      // "editorIndentGuide.background2"           : base.red.hex(),
      // "editorIndentGuide.background3"           : base.red.hex(),
      // "editorIndentGuide.background4"           : base.red.hex(),
      // "editorIndentGuide.background5"           : base.red.hex(),
      // "editorIndentGuide.background6"           : base.red.hex(),
      // "editorIndentGuide.activeBackground"      : base.red.hex(),
      // "editorIndentGuide.activeBackground1"     : base.red.hex(),
      // "editorIndentGuide.activeBackground2"     : base.red.hex(),
      // "editorIndentGuide.activeBackground3"     : base.red.hex(),
      // "editorIndentGuide.activeBackground4"     : base.red.hex(),
      // "editorIndentGuide.activeBackground5"     : base.red.hex(),
      // "editorIndentGuide.activeBackground6"     : base.red.hex(),
      // "editorInlayHint.background"              : base.red.hex(),
      // "editorInlayHint.foreground"              : base.red.hex(),
      // "editorInlayHint.typeForeground"          : base.red.hex(),
      // "editorInlayHint.typeBackground"          : base.red.hex(),
      // "editorInlayHint.parameterForeground"     : base.red.hex(),
      // "editorInlayHint.parameterBackground"     : base.red.hex(),
      // "editorRuler.foreground"                  : base.red.hex(),
      // "editor.linkedEditingBackground"          : base.red.hex(),
      // Editor Colors - Codelens
      // "editorCodeLens.foreground"               : base.red.hex(),
      // Editor Colors - Lightbulb
      // "editorLightBulb.foreground"              : base.red.hex(),
      // "editorLightBulbAutoFix.foreground"       : base.red.hex(),
      // "editorLightBulbAi.foreground"            : base.red.hex(),
      // Editor Colors - Matching Brackets
      "editorBracketMatch.background"                       : ui.message.info.normal.background.alpha(0.55).hex(),
      // "editorBracketMatch.border"                           : fg.hex(),
      "editorBracketHighlight.foreground1"                  : fg.hex(),
      "editorBracketHighlight.foreground2"                  : fg.hex(),
      "editorBracketHighlight.foreground3"                  : fg.hex(),
      "editorBracketHighlight.foreground4"                  : fg.hex(),
      "editorBracketHighlight.foreground5"                  : fg.hex(),
      "editorBracketHighlight.foreground6"                  : fg.hex(),
      "editorBracketHighlight.unexpectedBracket.foreground" : ui.message.error.normal.foreground.hex(),
      "editorBracketPairGuide.activeBackground1"            : base.green.alpha(0.55).hex(),
      "editorBracketPairGuide.activeBackground2"            : base.cyan.alpha(0.55).hex(),
      "editorBracketPairGuide.activeBackground3"            : base.blue.alpha(0.55).hex(),
      "editorBracketPairGuide.activeBackground4"            : base.magenta.alpha(0.55).hex(),
      "editorBracketPairGuide.activeBackground5"            : base.red.alpha(0.55).hex(),
      "editorBracketPairGuide.activeBackground6"            : base.yellow.alpha(0.55).hex(),
      "editorBracketPairGuide.background1"                  : base.green.alpha(0.35).hex(),
      "editorBracketPairGuide.background2"                  : base.cyan.alpha(0.35).hex(),
      "editorBracketPairGuide.background3"                  : base.blue.alpha(0.35).hex(),
      "editorBracketPairGuide.background4"                  : base.magenta.alpha(0.35).hex(),
      "editorBracketPairGuide.background5"                  : base.red.alpha(0.35).hex(),
      "editorBracketPairGuide.background6"                  : base.yellow.alpha(0.35).hex(),
      // Editor Colors - Folding
      // "editor.foldBackground"             : base.red.hex(),
      // "editor.foldPlaceholderForeground"  : base.red.hex(),
      // Editor Colors - Overview Ruler
      "editorOverviewRuler.background"                    : ui.panel.secondary.normal.background.alpha(0.35).hex(),
      // "editorOverviewRuler.border"                        : base.red.hex(),
      "editorOverviewRuler.findMatchForeground"           : ui.message.success.normal.foreground.hex(),
      "editorOverviewRuler.rangeHighlightForeground"      : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.selectionHighlightForeground"  : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.wordHighlightForeground"       : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.wordHighlightStrongForeground" : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.wordHighlightTextForeground"   : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.modifiedForeground"            : ui.git.modified.normal.foreground.hex(),
      "editorOverviewRuler.addedForeground"               : ui.git.added.normal.foreground.hex(),
      "editorOverviewRuler.deletedForeground"             : ui.git.deleted.normal.foreground.hex(),
      "editorOverviewRuler.errorForeground"               : ui.message.error.normal.foreground.hex(),
      "editorOverviewRuler.warningForeground"             : ui.message.warning.normal.foreground.hex(),
      "editorOverviewRuler.infoForeground"                : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.bracketMatchForeground"        : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.inlineChatInserted"            : ui.git.added.normal.foreground.hex(),
      "editorOverviewRuler.inlineChatRemoved"             : ui.git.added.normal.foreground.hex(),
      // Editor Colors - Errors and Warnings
      "editorError.foreground"          : ui.message.error.normal.foreground.hex(),
      // "editorError.border"              : ui.message.error.normal.border.hex(),
      "editorError.background"          : ui.message.error.normal.background.alpha(0.35).hex(),
      "editorWarning.foreground"        : ui.message.warning.normal.foreground.hex(),
      // "editorWarning.border"            : ui.message.warning.normal.border.hex(),
      "editorWarning.background"        : ui.message.warning.normal.background.alpha(0.35).hex(),
      "editorInfo.foreground"           : ui.message.info.normal.foreground.hex(),
      "editorInfo.border"               : ui.message.info.normal.border.hex(),
      "editorInfo.background"           : ui.message.info.normal.background.hex(),
      // "editorHint.foreground"           : base.red.hex(),
      // "editorHint.border"               : base.red.hex(),
      "problemsErrorIcon.foreground"    : ui.message.error.normal.foreground.hex(),
      "problemsWarningIcon.foreground"  : ui.message.warning.normal.foreground.hex(),
      "problemsInfoIcon.foreground"     : ui.message.info.normal.foreground.hex(),
      // Editor Colors - Unused Source Code
      "editorUnnecessaryCode.border"    : ui.message.warning.normal.border.hex(),
      "editorUnnecessaryCode.opacity"   : ui.message.warning.normal.border.hex(),
      // Editor Colors - Gutter
      "editorGutter.background"                       : ui.panel.secondary.normal.background.hex(),
      // "editorGutter.modifiedBackground"               : base.red.hex(),
      // "editorGutter.addedBackground"                  : base.green.hex(),
      // "editorGutter.deletedBackground"                : base.green.hex(),
      // "editorGutter.commentRangeForeground"           : base.red.hex(),
      // "editorGutter.commentGlyphForeground"           : base.red.hex(),
      // "editorGutter.commentUnresolvedGlyphForeground" : base.red.hex(),
      // "editorGutter.foldingControlForeground"         : base.red.hex(),
      // "editorCommentsWidget.resolvedBorder"           : base.red.hex(),
      // "editorCommentsWidget.unresolvedBorder"         : base.red.hex(),
      // "editorCommentsWidget.rangeBackground"          : base.red.hex(),
      // "editorCommentsWidget.rangeActiveBackground"    : base.red.hex(),
      // "editorCommentsWidget.replyInputBackground"     : base.red.hex(),
      // Diff Editor Colors
      "diffEditor.insertedTextBackground"       : ui.git.added.hovered.foreground.alpha(0.25).hex(),
      // "diffEditor.insertedTextBorder"           : ui.git.added.hovered.border.hex(),
      "diffEditor.removedTextBackground"        : ui.git.deleted.hovered.foreground.alpha(0.25).hex(),
      // "diffEditor.removedTextBorder"            : ui.git.deleted.hovered.border.hex(),
      // "diffEditor.border"                       : ui.panel.primary.normal.border.hex(),
      "diffEditor.diagonalFill"                 : ui.panel.primary.normal.background.hex(),
      "diffEditor.insertedLineBackground"       : ui.git.added.hovered.foreground.alpha(0.2).hex(),
      "diffEditor.removedLineBackground"        : ui.git.deleted.hovered.foreground.alpha(0.2).hex(),
      "diffEditorGutter.insertedLineBackground" : ui.git.added.hovered.foreground.alpha(0.2).hex(),
      "diffEditorGutter.removedLineBackground"  : ui.git.deleted.hovered.foreground.alpha(0.2).hex(),
      // "diffEditorOverview.insertedForeground"   : ui.git.added.normal.foreground.hex(),
      // "diffEditorOverview.removedForeground"    : ui.git.deleted.normal.foreground.hex(),
      // "diffEditor.unchangedRegionBackground"    : ui.panel.primary.normal.background.hex(),
      // "diffEditor.unchangedRegionForeground"    : ui.panel.primary.normal.foreground.hex(),
      // "diffEditor.unchangedRegionShadow"        : ui.panel.primary.normal.background.hex(),
      // "diffEditor.unchangedCodeBackground"      : ui.panel.primary.normal.background.hex(),
      // "diffEditor.move.border"                  : ui.panel.primary.normal.border.hex(),
      // "diffEditor.moveActive.border"            : ui.panel.primary.active.border.hex(),
      // "multiDiffEditor.headerBackground"        : ui.panel.primary.normal.background.hex(),
      // "multiDiffEditor.background"              : ui.panel.primary.normal.background.hex(),
      // "multiDiffEditor.border"                  : ui.panel.primary.normal.border.hex(),
      // Chat Colors
      "chat.requestBorder"          : ui.dialog.first.normal.border.hex(),
      "chat.requestBackground"      : ui.dialog.first.normal.background.hex(),
      "chat.slashCommandBackground" : ui.dialog.first.normal.background.hex(),
      "chat.slashCommandForeground" : ui.dialog.first.normal.foreground.hex(),
      "chat.avatarBackground"       : ui.dialog.first.normal.background.hex(),
      "chat.avatarForeground"       : ui.dialog.first.normal.foreground.hex(),
      // Inline Chat Colors
      "inlineChat.background"                 : ui.input.text.normal.background.hex(),
      "inlineChat.foreground"                 : ui.input.text.normal.foreground.hex(),
      "inlineChat.border"                     : ui.input.text.normal.border.hex(),
      "inlineChat.shadow"                     : ui.input.text.normal.background.hex(),
      "inlineChatInput.border"                : ui.input.text.normal.border.hex(),
      "inlineChatInput.focusBorder"           : ui.input.text.active.border.hex(),
      "inlineChatInput.placeholderForeground" : ui.input.text.normal.foreground.hex(),
      "inlineChatInput.background"            : ui.input.text.normal.background.hex(),
      "inlineChatDiff.inserted"               : ui.git.added.normal.background.hex(),
      "inlineChatDiff.removed"                : ui.git.deleted.normal.background.hex(),
      // Panel Chat Colors
      "interactive.activeCodeBorder"    : ui.dialog.first.active.background.hex(),
      "interactive.inactiveCodeBorder"  : ui.dialog.first.inactive.background.hex(),
      // Editor Widget Colors
      "editorWidget.foreground"                         : ui.dialog.first.normal.foreground.hex(),
      "editorWidget.background"                         : ui.dialog.first.normal.background.hex(),
      "editorWidget.border"                             : ui.dialog.first.normal.border.hex(),
      "editorWidget.resizeBorder"                       : ui.dialog.first.normal.border.hex(),
      "editorSuggestWidget.background"                  : ui.dialog.second.normal.background.hex(),
      "editorSuggestWidget.border"                      : ui.dialog.second.normal.border.hex(),
      "editorSuggestWidget.foreground"                  : ui.dialog.second.normal.foreground.hex(),
      "editorSuggestWidget.focusHightlightForeground"   : ui.dialog.second.active.foreground.hex(),
      "editorSuggestWidget.highlightForeground"         : ui.dialog.second.hovered.foreground.hex(),
      "editorSuggestWidget.selectedBackground"          : ui.dialog.second.active.background.hex(),
      "editorSuggestWidget.selectedForeground"          : ui.dialog.second.active.foreground.hex(),
      "editorSuggestWidget.selectedIconForeground"      : ui.dialog.second.active.foreground.hex(),
      "editorSuggestWidgetStatus.foreground"            : ui.dialog.second.active.foreground.hex(),
      "editorHoverWidget.foreground"                    : ui.dialog.first.normal.foreground.hex(),
      "editorHoverWidget.background"                    : ui.dialog.first.normal.background.hex(),
      "editorHoverWidget.border"                        : ui.dialog.first.normal.border.hex(),
      "editorHoverWidget.highlightForeground"           : ui.dialog.first.normal.foreground.hex(),
      "editorHoverWidget.statusBarBackground"           : ui.message.info.normal.background.hex(),
      "editorGhostText.border"                          : ui.dialog.third.normal.border.hex(),
      "editorGhostText.background"                      : ui.dialog.third.normal.background.hex(),
      "editorGhostText.foreground"                      : ui.dialog.third.normal.foreground.hex(),
      "editorStickyScroll.background"                   : ui.panel.secondary.normal.background.hex(),
      "editorStickyScroll.border"                       : ui.panel.secondary.normal.border.hex(),
      // "editorStickyScroll.shadow"                       : ui.dialog.third.normal.background.hex(),
      // "editorStickyScrollHover.background"              : ui.dialog.third.hovered.background.hex(),
      "debugExceptionWidget.background"                 : ui.message.error.normal.background.hex(),
      "debugExceptionWidget.border"                     : ui.message.error.normal.border.hex(),
      "editorMarkerNavigation.background"               : ui.dialog.first.normal.background.hex(),
      "editorMarkerNavigationError.background"          : ui.message.error.normal.background.hex(),
      "editorMarkerNavigationWarning.background"        : ui.message.warning.normal.background.hex(),
      "editorMarkerNavigationInfo.background"           : ui.message.info.normal.background.hex(),
      "editorMarkerNavigationError.headerBackground"    : ui.message.error.normal.background.hex(),
      "editorMarkerNavigationWarning.headerBackground"  : ui.message.warning.normal.background.hex(),
      "editorMarkerNavigationInfo.headerBackground"     : ui.message.info.normal.background.hex(),
      // Peek View Colors
      "peekView.border"                         : ui.dialog.first.normal.border.hex(),
      "peekViewEditor.background"               : ui.dialog.first.normal.background.hex(),
      "peekViewEditorGutter.background"         : ui.dialog.first.normal.background.hex(),
      "peekViewEditor.matchHighlightBackground" : ui.dialog.first.active.background.hex(),
      "peekViewEditor.matchHighlightBorder"     : ui.dialog.first.active.border.hex(),
      "peekViewResult.background"               : ui.dialog.first.normal.background.hex(),
      "peekViewResult.fileForeground"           : ui.dialog.first.normal.foreground.hex(),
      "peekViewResult.lineForeground"           : ui.dialog.first.inactive.foreground.hex(),
      "peekViewResult.matchHighlightBackground" : ui.dialog.first.active.foreground.hex(),
      "peekViewResult.selectionBackground"      : ui.dialog.first.active.background.hex(),
      "peekViewResult.selectionForeground"      : ui.dialog.first.active.foreground.hex(),
      "peekViewTitle.background"                : ui.dialog.first.normal.background.hex(),
      "peekViewTitleDescription.foreground"     : ui.dialog.first.normal.foreground.hex(),
      "peekViewTitleLabel.foreground"           : ui.dialog.first.normal.foreground.hex(),
      "peekViewEditorStickyScroll.background"   : ui.dialog.first.normal.background.hex(),
      // Merge Conflicts Colors
      "merge.currentHeaderBackground"                       : ui.message.info.normal.background.alpha(0.75).hex(),
      "merge.currentContentBackground"                      : ui.message.info.normal.background.alpha(0.95).hex(),
      "merge.incomingHeaderBackground"                      : ui.message.warning.normal.background.alpha(0.55).hex(),
      "merge.incomingContentBackground"                     : ui.message.warning.normal.background.alpha(0.75).hex(),
      // "merge.border"                                        : fg.hex(),
      "merge.commonContentBackground"                       : ui.message.info.normal.background.alpha(0.75).hex(),
      "merge.commonHeaderBackground"                        : ui.message.info.normal.background.alpha(0.55).hex(),
      "editorOverviewRuler.currentContentForeground"        : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.incomingContentForeground"       : ui.message.warning.normal.foreground.hex(),
      "editorOverviewRuler.commonContentForeground"         : ui.message.info.normal.foreground.hex(),
      "editorOverviewRuler.commentForeground"               : ui.git.conflicted.normal.foreground.hex(),
      "editorOverviewRuler.commentUnresolvedForeground"     : ui.git.conflicted.normal.foreground.hex(),
      "mergeEditor.change.background"                       : ui.git.conflicted.normal.background.hex(),
      "mergeEditor.change.word.background"                  : ui.git.conflicted.normal.background.hex(),
      // "mergeEditor.conflict.unhandledUnfocused.border"      : base.red.hex(),
      // "mergeEditor.conflict.unhandledFocused.border"        : base.red.hex(),
      // "mergeEditor.conflict.handledUnfocused.border"        : base.red.hex(),
      // "mergeEditor.conflict.handledFocused.border"          : base.red.hex(),
      "mergeEditor.conflict.handled.minimapOverViewRuler"   : ui.git.added.normal.background.hex(),
      "mergeEditor.conflict.unhandled.minimapOverViewRuler" : ui.git.conflicted.normal.background.hex(),
      "mergeEditor.conflictingLines.background"             : ui.git.conflicted.normal.background.hex(),
      // "mergeEditor.changeBase.background"                   : base.red.hex(),
      // "mergeEditor.changeBase.word.background"              : base.red.hex(),
      // "mergeEditor.conflict.input1.background"              : base.red.hex(),
      // "mergeEditor.conflict.input2.background"              : base.red.hex(),
      // Panel Colors
      "panel.background"                  : ui.panel.secondary.normal.background.hex(),
      // "panel.border"                      : base.red.hex(),
      // "panel.dropBorder"                  : base.red.hex(),
      // "panelTitle.activeBorder"           : base.red.hex(),
      // "panelTitle.activeForeground"       : ui.panel.secondary.active.foreground.hex(),
      // "panelTitle.inactiveForeground"     : ui.panel.secondary.inactive.foreground.hex(),
      // "panelInput.border"                 : base.red.hex(),
      // "panelSection.border"               : base.red.hex(),
      "panelSection.dropBackground"       : ui.panel.tertiary.normal.background.hex(),
      "panelSectionHeader.background"     : ui.panel.tertiary.normal.background.hex(),
      // "panelSectionHeader.foreground"     : ui.panel.tertiary.normal.foreground.hex(),
      "panelStickyScroll.background"      : ui.panel.secondary.normal.background.hex(),
      // "panelStickyScroll.border"          : base.red.hex(),
      // "panelStickyScroll.shadow"          : base.red.hex(),
      // "panelSectionHeader.border"         : ui.panel.secondary.normal.border.hex(),
      "outputView.background"             : ui.panel.secondary.normal.background.hex(),
      "outputViewStickyScroll.background" : ui.panel.secondary.normal.background.hex(),
      // Status Bar Colors
      "statusBar.background"                    : ui.panel.tertiary.normal.background.hex(),
      "statusBar.foreground"                    : ui.panel.tertiary.normal.foreground.hex(),
      // "statusBar.border"                        : base.red.hex(),
      "statusBar.debuggingBackground"           : ui.message.warning.normal.background.hex(),
      "statusBar.debuggingForeground"           : ui.message.warning.normal.foreground.hex(),
      // "statusBar.debuggingBorder"               : base.red.hex(),
      // "statusBar.noFolderForeground"            : base.red.hex(),
      // "statusBar.noFolderBackground"            : base.red.hex(),
      // "statusBar.noFolderBorder"                : base.red.hex(),
      // "statusBarItem.activeBackground"          : base.red.hex(),
      "statusBarItem.hoverForeground"           : ui.panel.tertiary.hovered.foreground.hex(),
      "statusBarItem.hoverBackground"           : ui.panel.tertiary.hovered.background.hex(),
      "statusBarItem.prominentForeground"       : ui.panel.primary.normal.foreground.hex(),
      "statusBarItem.prominentBackground"       : ui.panel.primary.normal.background.hex(),
      "statusBarItem.prominentHoverForeground"  : ui.panel.primary.hovered.foreground.hex(),
      "statusBarItem.prominentHoverBackground"  : ui.panel.primary.hovered.background.hex(),
      "statusBarItem.remoteBackground"          : ui.message.info.normal.background.hex(),
      "statusBarItem.remoteForeground"          : ui.message.info.normal.foreground.hex(),
      "statusBarItem.remoteHoverBackground"     : ui.message.info.hovered.background.hex(),
      "statusBarItem.remoteHoverForeground"     : ui.message.info.hovered.foreground.hex(),
      "statusBarItem.errorBackground"           : ui.message.error.normal.background.hex(),
      "statusBarItem.errorForeground"           : ui.message.error.normal.foreground.hex(),
      "statusBarItem.errorHoverBackground"      : ui.message.error.hovered.background.hex(),
      "statusBarItem.errorHoverForeground"      : ui.message.error.hovered.foreground.hex(),
      "statusBarItem.warningBackground"         : ui.message.warning.normal.background.hex(),
      "statusBarItem.warningForeground"         : ui.message.warning.normal.foreground.hex(),
      "statusBarItem.warningHoverBackground"    : ui.message.warning.hovered.background.hex(),
      "statusBarItem.warningHoverForeground"    : ui.message.warning.hovered.foreground.hex(),
      "statusBarItem.compactHoverBackground"    : ui.panel.tertiary.hovered.background.hex(),
      // "statusBarItem.focusBorder"               : base.red.hex(),
      // "statusBar.focusBorder"                   : base.red.hex(),
      // "statusBarItem.offlineBackground"         : base.red.hex(),
      // "statusBarItem.offlineForeground"         : base.red.hex(),
      // "statusBarItem.offlineHoverForeground"    : base.red.hex(),
      // "statusBarItem.offlineHoverBackground"    : base.red.hex(),
      // Title Bar Colors
      "titleBar.activeBackground"     : ui.panel.secondary.normal.background.hex(),
      "titleBar.activeForeground"     : ui.panel.secondary.normal.foreground.hex(),
      "titleBar.inactiveBackground"   : ui.panel.secondary.inactive.background.hex(),
      "titleBar.inactiveForeground"   : ui.panel.secondary.inactive.foreground.hex(),
      // "titleBar.border"               : base.red.hex(),
      // Menu Bar Colors
      "menubar.selectionForeground" : ui.panel.tertiary.hovered.foreground.hex(),
      "menubar.selectionBackground" : ui.panel.tertiary.hovered.background.hex(),
      // "menubar.selectionBorder"     : base.red.hex(),
      "menu.foreground"             : ui.panel.tertiary.normal.foreground.hex(),
      "menu.background"             : ui.panel.tertiary.normal.background.hex(),
      "menu.selectionForeground"    : ui.panel.tertiary.hovered.foreground.hex(),
      "menu.selectionBackground"    : ui.panel.tertiary.hovered.background.hex(),
      // "menu.selectionBorder"        : base.red.hex(),
      "menu.separatorBackground"    : ui.panel.tertiary.normal.background.hex(),
      // "menu.border"                 : base.red.hex(),
      // Command Center Colors
      "commandCenter.foreground"          : ui.input.text.normal.foreground.hex(),
      "commandCenter.activeForeground"    : ui.input.text.active.foreground.hex(),
      "commandCenter.background"          : ui.input.text.normal.background.hex(),
      "commandCenter.activeBackground"    : ui.input.text.active.background.hex(),
      // "commandCenter.border"              : base.red.hex(),
      "commandCenter.inactiveForeground"  : ui.input.text.inactive.foreground.hex(),
      // "commandCenter.inactiveBorder"      : base.red.hex(),
      "commandCenter.activeBorder"        : ui.input.text.active.border.hex(),
      // "commandCenter.debuggingBackground" : base.red.hex(),
      // Notification Colors
      // "notificationCenter.border"           : base.red.hex(),
      "notificationCenterHeader.foreground" : ui.dialog.first.normal.foreground.hex(),
      "notificationCenterHeader.background" : ui.dialog.first.normal.background.hex(),
      // "notificationToast.border"            : base.red.hex(),
      "notifications.foreground"            : ui.dialog.second.normal.foreground.hex(),
      "notifications.background"            : ui.dialog.second.normal.background.hex(),
      // "notifications.border"                : base.red.hex(),
      "notificationLink.foreground"         : ui.message.info.normal.foreground.hex(),
      "notificationsErrorIcon.foreground"   : ui.message.error.normal.foreground.hex(),
      "notificationsWarningIcon.foreground" : ui.message.warning.normal.foreground.hex(),
      "notificationsInfoIcon.foreground"    : ui.message.info.normal.foreground.hex(),
      // Banner Colors
      // "banner.background"     : base.red.hex(),
      // "banner.foreground"     : base.red.hex(),
      // "banner.iconForeground" : base.red.hex(),
      // Extension Colors
      // "extensionButton.prominentForeground"       : base.red.hex(),
      // "extensionButton.prominentBackground"       : base.red.hex(),
      // "extensionButton.prominentHoverBackground"  : base.red.hex(),
      // "extensionButton.background"                : base.red.hex(),
      // "extensionButton.foreground"                : base.red.hex(),
      // "extensionButton.hoverBackground"           : base.red.hex(),
      // "extensionButton.separator"                 : base.red.hex(),
      // "extensionBadge.remoteBackground"           : base.red.hex(),
      // "extensionBadge.remoteForeground"           : base.red.hex(),
      // "extensionIcon.starForeground"              : base.red.hex(),
      // "extensionIcon.verifiedForeground"          : base.red.hex(),
      // "extensionIcon.preReleaseForeground"        : base.red.hex(),
      // "extensionIcon.sponsorForeground"           : base.red.hex(),
      // Quick Picker Colors
      "pickerGroup.border"                  : ui.panel.tertiary.normal.border.hex(),
      "pickerGroup.foreground"              : ui.panel.tertiary.active.foreground.hex(),
      "quickInput.background"               : ui.panel.tertiary.normal.background.hex(),
      "quickInput.foreground"               : ui.panel.tertiary.normal.foreground.hex(),
      "quickInputList.focusBackground"      : ui.panel.tertiary.active.background.hex(),
      "quickInputList.focusForeground"      : ui.panel.tertiary.active.foreground.hex(),
      "quickInputList.focusIconForeground"  : ui.panel.tertiary.active.foreground.hex(),
      "quickInputTitle.background"          : ui.panel.tertiary.normal.background.hex(),
      // Keybinding Label Colors
      "keybindingLabel.background"        : ui.input.button.normal.background.hex(),
      "keybindingLabel.foreground"        : ui.input.button.normal.foreground.hex(),
      // "keybindingLabel.border"            : base.red.hex(),
      // "keybindingLabel.bottomBorder"      : base.red.hex(),
      // "keybindingTable.headerBackground"  : base.red.hex(),
      // "keybindingTable.rowsBackground"    : base.red.hex(),
      // Integrated Terminal Colors
      "terminal.background"                         : ui.panel.tertiary.normal.background.hex(),
      // "terminal.border"                             : fg.hex(),
      "terminal.foreground"                         : ui.panel.tertiary.normal.foreground.hex(),
      "terminal.ansiBlack"                          : base.black.hex(),
      "terminal.ansiBlue"                           : base.blue.hex(),
      "terminal.ansiBrightBlack"                    : base.blackBright.hex(),
      "terminal.ansiBrightBlue"                     : base.blueBright.hex(),
      "terminal.ansiBrightCyan"                     : base.cyanBright.hex(),
      "terminal.ansiBrightGreen"                    : base.greenBright.hex(),
      "terminal.ansiBrightMagenta"                  : base.magentaBright.hex(),
      "terminal.ansiBrightRed"                      : base.redBright.hex(),
      "terminal.ansiBrightWhite"                    : base.whiteBright.hex(),
      "terminal.ansiBrightYellow"                   : base.yellowBright.hex(),
      "terminal.ansiCyan"                           : base.cyan.hex(),
      "terminal.ansiGreen"                          : base.green.hex(),
      "terminal.ansiMagenta"                        : base.magenta.hex(),
      "terminal.ansiRed"                            : base.red.hex(),
      "terminal.ansiWhite"                          : base.white.hex(),
      "terminal.ansiYellow"                         : base.yellow.hex(),
      "terminal.selectionBackground"                : ui.panel.primary.active.foreground.alpha(0.1).hex(),
      // "terminal.selectionForeground"                : fg.hex(),
      "terminal.inactiveSelectionBackground"        : ui.panel.primary.inactive.foreground.alpha(0.1).hex(),
      "terminal.findMatchBackground"                : ui.message.info.inactive.foreground.alpha(0.1).hex(),
      // "terminal.findMatchBorder"                    : fg.hex(),
      "terminal.findMatchHighlightBackground"       : ui.message.info.active.foreground.alpha(0.1).hex(),
      // "terminal.findMatchHighlightBorder"           : fg.hex(),
      "terminal.hoverHighlightBackground"           : ui.message.info.hovered.foreground.alpha(0.1).hex(),
      "terminalCursor.background"                   : ui.panel.tertiary.normal.background.hex(),
      "terminalCursor.foreground"                   : ui.panel.tertiary.active.foreground.hex(),
      "terminal.dropBackground"                     : fg.hex(),
      "terminal.tab.activeBorder"                   : ui.panel.tertiary.active.background.hex(),
      "terminalCommandDecoration.defaultBackground" : fg.hex(),
      "terminalCommandDecoration.successBackground" : fg.hex(),
      "terminalCommandDecoration.errorBackground"   : fg.hex(),
      "terminalOverviewRuler.cursorForeground"      : fg.hex(),
      "terminalOverviewRuler.findMatchForeground"   : fg.hex(),
      "terminalStickyScroll.background"             : fg.hex(),
      "terminalStickyScroll.border"                 : fg.hex(),
      "terminalStickyScrollHover.background"        : fg.hex(),
      "terminal.initialHintForeground"              : fg.hex(),
      "terminalOverviewRuler.border"                : fg.hex(),
      "terminalCommandGuide.foreground"             : fg.hex(),
      // Debug Colors
      "debugToolBar.background"                     : ui.message.warning.inactive.background.hex(),
      // "debugToolBar.border"                         : base.red.hex(),
      "editor.stackFrameHighlightBackground"        : ui.message.info.normal.background.alpha(0.95).hex(),
      "editor.focusedStackFrameHighlightBackground" : ui.message.info.normal.background.alpha(0.95).hex(),
      "editor.inlineValuesForeground"               : syntax.number.hex(),
      "editor.inlineValuesBackground"               : ui.message.warning.normal.background.hex(),
      "debugView.exceptionLabelForeground"          : ui.message.warning.normal.foreground.hex(),
      "debugView.exceptionLabelBackground"          : ui.message.warning.normal.background.hex(),
      "debugView.stateLabelForeground"              : ui.message.error.normal.foreground.hex(),
      "debugView.stateLabelBackground"              : ui.message.error.normal.background.hex(),
      "debugView.valueChangedHighlight"             : ui.message.info.normal.background.hex(),
      "debugTokenExpression.name"                   : syntax.variable.hex(),
      "debugTokenExpression.value"                  : syntax.variable.hex(),
      "debugTokenExpression.string"                 : syntax.string.hex(),
      "debugTokenExpression.boolean"                : syntax.keyword.hex(),
      "debugTokenExpression.number"                 : syntax.number.hex(),
      "debugTokenExpression.error"                  : ui.message.error.normal.foreground.hex(),
      "debugTokenExpression.type"                   : syntax.type.hex(),
      // Testing Colors
      // "testing.runAction"                           : fg.hex(),
      // "testing.iconErrored"                         : fg.hex(),
      // "testing.iconFailed"                          : fg.hex(),
      // "testing.iconPassed"                          : fg.hex(),
      // "testing.iconQueued"                          : fg.hex(),
      // "testing.iconUnset"                           : fg.hex(),
      // "testing.iconSkipped"                         : fg.hex(),
      // "testing.iconErrored.retired"                 : fg.hex(),
      // "testing.iconFailed.retired"                  : fg.hex(),
      // "testing.iconPassed.retired"                  : fg.hex(),
      // "testing.iconQueued.retired"                  : fg.hex(),
      // "testing.iconUnset.retired"                   : fg.hex(),
      // "testing.iconSkipped.retired"                 : fg.hex(),
      // "testing.peekBorder"                          : fg.hex(),
      // "testing.peekHeaderBackground"                : fg.hex(),
      // "testing.message.error.decorationForeground"  : fg.hex(),
      // "testing.message.error.lineBackground"        : fg.hex(),
      // "testing.message.info.decorationForeground"   : fg.hex(),
      // "testing.message.info.lineBackground"         : fg.hex(),
      // "testing.messagePeekBorder"                   : fg.hex(),
      // "testing.messagePeekHeaderBackground"         : fg.hex(),
      // "testing.coveredBackground"                   : fg.hex(),
      // "testing.coveredBorder"                       : fg.hex(),
      // "testing.coveredGutterBackground"             : fg.hex(),
      // "testing.uncoveredBranchBackground"           : fg.hex(),
      // "testing.uncoveredBackground"                 : fg.hex(),
      // "testing.uncoveredBorder"                     : fg.hex(),
      // "testing.uncoveredGutterBackground"           : fg.hex(),
      // "testing.coverCountBadgeBackground"           : fg.hex(),
      // "testing.coverCountBadgeForeground"           : fg.hex(),
      // Welcome Page Colors
      // "welcomePage.background"                : fg.hex(),
      // "welcomePage.progress.background"       : fg.hex(),
      // "welcomePage.progress.foreground"       : fg.hex(),
      // "welcomePage.tileBackground"            : fg.hex(),
      // "welcomePage.tileHoverBackground"       : fg.hex(),
      // "welcomePage.tileBorder"                : fg.hex(),
      // "walkThrough.embeddedEditorBackground"  : fg.hex(),
      // "walkthrough.stepTitle.foreground"      : fg.hex(),
      // Git Colors
      "gitDecoration.addedResourceForeground"         : ui.git.added.normal.foreground.hex(),
      "gitDecoration.modifiedResourceForeground"      : ui.git.modified.normal.foreground.hex(),
      "gitDecoration.deletedResourceForeground"       : ui.git.deleted.normal.foreground.hex(),
      "gitDecoration.renamedResourceForeground"       : ui.git.modified.normal.foreground.hex(),
      "gitDecoration.stageModifiedResourceForeground" : ui.git.modified.active.foreground.hex(),
      "gitDecoration.stageDeletedResourceForeground"  : ui.git.deleted.active.foreground.hex(),
      "gitDecoration.untrackedResourceForeground"     : ui.git.untracked.normal.foreground.hex(),
      "gitDecoration.ignoredResourceForeground"       : ui.git.untracked.normal.foreground.hex(),
      "gitDecoration.conflictingResourceForeground"   : ui.message.error.normal.foreground.hex(),
      "gitDecoration.submoduleResourceForeground"     : fg.hex(),
      // Source Control Graph Colors
      "scmGraph.historyItemGroupLocal"                : fg.hex(),
      "scmGraph.historyItemGroupRemote"               : fg.hex(),
      "scmGraph.historyItemGroupBase"                 : fg.hex(),
      "scmGraph.historyItemHoverLabelForeground"      : fg.hex(),
      "scmGraph.historyItemHoverAdditionsForeground"  : ui.git.added.hovered.foreground.hex(),
      "scmGraph.historyItemHoverDeletionsForeground"  : ui.git.deleted.hovered.foreground.hex(),
      // Settings Editor Colors
      // "settings.headerForeground"               : base.red.hex(),
      // "settings.modifiedItemIndicator"          : base.red.hex(),
      // "settings.dropdownBackground"             : base.red.hex(),
      // "settings.dropdownForeground"             : base.red.hex(),
      // "settings.dropdownBorder"                 : base.red.hex(),
      // "settings.dropdownListBorder"             : base.red.hex(),
      // "settings.checkboxBackground"             : base.red.hex(),
      // "settings.checkboxForeground"             : base.red.hex(),
      // "settings.checkboxBorder"                 : base.red.hex(),
      // "settings.rowHoverBackground"             : base.red.hex(),
      // "settings.textInputBackground"            : base.red.hex(),
      // "settings.textInputForeground"            : base.red.hex(),
      // "settings.textInputBorder"                : base.red.hex(),
      // "settings.numberInputBackground"          : base.red.hex(),
      // "settings.numberInputForeground"          : base.red.hex(),
      // "settings.numberInputBorder"              : base.red.hex(),
      // "settings.focusedRowBackground"           : base.red.hex(),
      // "settings.focusedRowBorder"               : base.red.hex(),
      // "settings.headerBorder"                   : base.red.hex(),
      // "settings.sashBorder"                     : base.red.hex(),
      // "settings.settingsHeaderHoverForeground"  : base.red.hex(),
      // Breadcrumbs Colors
      "breadcrumb.foreground"                 : ui.bar.tertiary.normal.foreground.hex(),
      "breadcrumb.background"                 : ui.bar.tertiary.normal.background.hex(),
      // "breadcrumb.focusForeground"            : base.red.hex(),
      // "breadcrumb.activeSelectionForeground"  : base.red.hex(),
      // "breadcrumbPicker.background"           : base.red.hex(),
      // // Snippets Colors
      // "editor.snippetTabstopHighlightBackground"      : base.red.hex(),
      // "editor.snippetTabstopHighlightBorder"          : base.red.hex(),
      // "editor.snippetFinalTabstopHighlightBackground" : base.red.hex(),
      // "editor.snippetFinalTabstopHighlightBorder"     : base.red.hex(),
      // Symbol Icons Colors
      // "symbolIcon.arrayForeground"            : base.red.hex(),
      // "symbolIcon.booleanForeground"          : base.red.hex(),
      // "symbolIcon.classForeground"            : base.red.hex(),
      // "symbolIcon.colorForeground"            : base.red.hex(),
      // "symbolIcon.constantForeground"         : base.red.hex(),
      // "symbolIcon.constructorForeground"      : base.red.hex(),
      // "symbolIcon.enumeratorForeground"       : base.red.hex(),
      // "symbolIcon.enumeratorMemberForeground" : base.red.hex(),
      // "symbolIcon.eventForeground"            : base.red.hex(),
      // "symbolIcon.fieldForeground"            : base.red.hex(),
      // "symbolIcon.fileForeground"             : base.red.hex(),
      // "symbolIcon.folderForeground"           : base.red.hex(),
      // "symbolIcon.functionForeground"         : base.red.hex(),
      // "symbolIcon.interfaceForeground"        : base.red.hex(),
      // "symbolIcon.keyForeground"              : base.red.hex(),
      // "symbolIcon.keywordForeground"          : base.red.hex(),
      // "symbolIcon.methodForeground"           : base.red.hex(),
      // "symbolIcon.moduleForeground"           : base.red.hex(),
      // "symbolIcon.namespaceForeground"        : base.red.hex(),
      // "symbolIcon.nullForeground"             : base.red.hex(),
      // "symbolIcon.numberForeground"           : base.red.hex(),
      // "symbolIcon.objectForeground"           : base.red.hex(),
      // "symbolIcon.operatorForeground"         : base.red.hex(),
      // "symbolIcon.packageForeground"          : base.red.hex(),
      // "symbolIcon.propertyForeground"         : base.red.hex(),
      // "symbolIcon.referenceForeground"        : base.red.hex(),
      // "symbolIcon.snippetForeground"          : base.red.hex(),
      // "symbolIcon.stringForeground"           : base.red.hex(),
      // "symbolIcon.structForeground"           : base.red.hex(),
      // "symbolIcon.textForeground"             : base.red.hex(),
      // "symbolIcon.typeParameterForeground"    : base.red.hex(),
      // "symbolIcon.unitForeground"             : base.red.hex(),
      // "symbolIcon.variableForeground"         : base.red.hex(),
      // Debug Icons Colors
      // "debugIcon.breakpointForeground"                  : base.red.hex(),
      // "debugIcon.breakpointDisabledForeground"          : base.red.hex(),
      // "debugIcon.breakpointUnverifiedForeground"        : base.red.hex(),
      // "debugIcon.breakpointCurrentStackframeForeground" : base.red.hex(),
      // "debugIcon.breakpointStackframeForeground"        : base.red.hex(),
      "debugIcon.startForeground"                       : ui.message.success.normal.foreground.hex(),
      "debugIcon.pauseForeground"                       : fg.hex(),
      "debugIcon.stopForeground"                        : ui.message.error.normal.foreground.hex(),
      "debugIcon.disconnectForeground"                  : fg.hex(),
      "debugIcon.restartForeground"                     : ui.message.success.normal.foreground.hex(),
      "debugIcon.stepOverForeground"                    : fg.hex(),
      "debugIcon.stepIntoForeground"                    : fg.hex(),
      "debugIcon.stepOutForeground"                     : fg.hex(),
      "debugIcon.continueForeground"                    : fg.hex(),
      "debugIcon.stepBackForeground"                    : fg.hex(),
      "debugConsole.infoForeground"                     : ui.message.info.normal.foreground.hex(),
      "debugConsole.warningForeground"                  : ui.message.warning.normal.foreground.hex(),
      "debugConsole.errorForeground"                    : ui.message.error.normal.foreground.hex(),
      "debugConsole.sourceForeground"                   : fg.hex(),
      "debugConsoleInputIcon.foreground"                : fg.hex(),
      // Notebook Colors
      // "notebook.editorBackground"                         : base.red.hex(),
      // "notebook.cellBorderColor"                          : base.red.hex(),
      // "notebook.cellHoverBackground"                      : base.red.hex(),
      // "notebook.cellInsertionIndicator"                   : base.red.hex(),
      // "notebook.cellStatusBarItemHoverBackground"         : base.red.hex(),
      // "notebook.cellToolbarSeparator"                     : base.red.hex(),
      // "notebook.cellEditorBackground"                     : base.red.hex(),
      // "notebook.focusedCellBackground"                    : base.red.hex(),
      // "notebook.focusedCellBorder"                        : base.red.hex(),
      // "notebook.focusedEditorBorder"                      : base.red.hex(),
      // "notebook.inactiveFocusedCellBorder"                : base.red.hex(),
      // "notebook.inactiveSelectedCellBorder"               : base.red.hex(),
      // "notebook.outputContainerBackgroundColor"           : base.red.hex(),
      // "notebook.outputContainerBorderColor"               : base.red.hex(),
      // "notebook.selectedCellBackground"                   : base.red.hex(),
      // "notebook.selectedCellBorder"                       : base.red.hex(),
      // "notebook.symbolHighlightBackground"                : base.red.hex(),
      // "notebookScrollbarSlider.activeBackground"          : base.red.hex(),
      // "notebookScrollbarSlider.background"                : base.red.hex(),
      // "notebookScrollbarSlider.hoverBackground"           : base.red.hex(),
      // "notebookStatusErrorIcon.foreground"                : base.red.hex(),
      // "notebookStatusRunningIcon.foreground"              : base.red.hex(),
      // "notebookStatusSuccessIcon.foreground"              : base.red.hex(),
      // "notebookEditorOverviewRuler.runningCellForeground" : base.red.hex(),
      // Chart Colors
      // "charts.foreground" : base.red.hex(),
      // "charts.lines"      : base.red.hex(),
      // "charts.red"        : base.red.hex(),
      // "charts.blue"       : base.red.hex(),
      // "charts.yellow"     : base.red.hex(),
      // "charts.orange"     : base.red.hex(),
      // "charts.green"      : base.red.hex(),
      // "charts.purple"     : base.red.hex(),
      // Ports Colors
      // "ports.iconRunningProcessForeground"  : base.red.hex(),
      // Comments View Colors
      // "commentsView.resolvedIcon"   : base.red.hex(),
      // "commentsView.unresolvedIcon" : base.red.hex(),
      // "actionBar.toggledBackground" : base.red.hex(),
      // Simple Find Widget
      // "simpleFindWidget.sashBorder"             : base.red.hex(),
      // SCM
      // "scm.historyItemAdditionsForeground"      : base.red.hex(),
      // "scm.historyItemDeletionsForeground"      : base.red.hex(),
      // "scm.historyItemStatisticsBorder"         : base.red.hex(),
      // "scm.historyItemSelectedStatisticsBorder" : base.red.hex(),
    }
  }
}
